services:
  - type: web
    name: fastapi-summarizer
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: AWS_ACCESS_KEY_ID
        value: your-aws-access-key
      - key: AWS_SECRET_ACCESS_KEY
        value: your-aws-secret-key
      - key: AWS_REGION
        value: your-region
      - key: AWS_S3_BUCKET
        value: your-bucket-name
      - key: GEMINI_API_KEY
        value: your-gemini-api-key
      - key: SERPAPI_API_KEY
        value: your-serpapi-key
